Fixing crash(es)
sdsmdg/calling_text pull request #6
Opened 2018-03-26 17:16 UTC by narendrakpatel

:bug:  fixed crash on opening app without permissions 
:bug:  fixed crash on opening gif
:art:  slight UI improvement

2018-03-29 13:45 UTC, Mansi449 requested changes
Good work! But do make the requested changes.

2018-03-29 13:45 UTC, Mansi449 commented on app/src/main/java/com/sdsmdg/pulkit/callingtext/BaseActivity.java
> +        Log.d("lololo", "took permissions");
Define and use a proper LOG_TAG here. See this https://developer.android.com/reference/android/util/Log.html

2018-03-29 13:45 UTC, Mansi449 commented on app/src/main/java/com/sdsmdg/pulkit/callingtext/BaseActivity.java
> +                    Log.d("lololo", String.valueOf(grantResult));
Use LOG_TAG

2018-03-29 13:45 UTC, Mansi449 commented on app/src/main/java/com/sdsmdg/pulkit/callingtext/ContactListFragment.java
> +import android.*;
This import statement is not needed. Remove it.

2018-03-29 13:45 UTC, Mansi449 commented on app/src/main/java/com/sdsmdg/pulkit/callingtext/ContactListFragment.java
> +import android.support.v4.content.ContextCompat;
Not needed

2018-03-29 19:14 UTC, Mansi449 requested changes

2018-03-29 19:14 UTC, Mansi449 commented on build.gradle
Why these blank lines

2018-03-29 19:14 UTC, Mansi449 commented on build.gradle
remove blank line

2018-03-30 11:07 UTC, narendrakpatel commented
I have done the changes.
Are there any other changes that i should do?

2018-04-02 13:06 UTC, Mansi449 approved these changes

2018-04-02 13:07 UTC, Mansi449 commented
No, it's enough okay for now.

2018-05-08 06:48 UTC, merged